"""
Phase 5 — Batch Generator.

Builds a training batch for one sleep cycle from:
  • New (un-consolidated) memories for the current 3-day window
  • Replay sample from previously consolidated memories
  • Optional regularizer exchanges to preserve assistant formatting

Returned format: list of HuggingFace chat-format message lists
  [ [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}], ... ]

Mixture ratios (applied per new memory item):
  40% declarative  — flat "Remember: Subject predicate value." exchange
  40% QA           — question/answer filled strictly from train_config qa_train_templates
  20% dialogue     — 2–3 turn snippet from the raw dialogue log proving the fact

Replay buffer:
  Weighted random sample from all consolidated memories.
  Weight = salience_score × temporal_decay (both stored in memories JSONL from Phase 4).

Regularizer:
  10 generic Llama-3 assistant exchanges hardcoded here. These are drawn
  from the training distribution to prevent the model from collapsing into
  a pure fact-spitting format.

Test leakage prevention:
  QA templates come ONLY from train_config["qa_train_templates"]. This file
  is generated by the runner, never modified here. Phase 7 uses a completely
  separate eval template list defined in eval_config.json.
"""

from __future__ import annotations

import json
import random
from typing import Any

# Reuse the same category mapper and token extractor used in Phase 3/4
# so that the replay-weighting and QA category labelling are consistent.
from ..salience.score import _map_category, _primary_tokens

# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

_SYS_REMEMBER = (
    "You are a helpful AI assistant that remembers personal information "
    "about users. Retain the following fact accurately."
)
_SYS_RECALL = (
    "You are a helpful AI assistant with access to personal information "
    "about users. Answer questions based on what you know about them."
)

# ---------------------------------------------------------------------------
# Regularizer exchanges (generic, persona-neutral Llama-3 style)
# ---------------------------------------------------------------------------

_REGULARIZER_EXCHANGES: list[tuple[str, str]] = [
    (
        "Hello! How can I help you today?",
        "Hi there! I'm happy to assist. What's on your mind?",
    ),
    (
        "Can you help me write an email?",
        "Of course! Tell me who it's to and what you'd like to say.",
    ),
    (
        "What's a good way to stay focused while working?",
        "Try breaking your work into smaller tasks and taking short breaks. "
        "The Pomodoro technique works well for many people.",
    ),
    (
        "Tell me something interesting.",
        "Did you know that honey never spoils? Archaeologists have found "
        "3,000-year-old honey in Egyptian tombs that was still perfectly edible.",
    ),
    (
        "I'm not sure what to do today.",
        "Sometimes starting with something small builds momentum. "
        "Is there a task you've been putting off?",
    ),
    (
        "Can you recommend a good book?",
        "It depends on your interests! For literary fiction, 'The Remains of the Day' "
        "by Kazuo Ishiguro is wonderful. What genres do you enjoy?",
    ),
    (
        "I feel like I need a break.",
        "That sounds healthy. Even a short walk or a few minutes away from "
        "screens can reset your focus.",
    ),
    (
        "What time is it?",
        "I don't have access to real-time data, but your device's clock "
        "should have the current time!",
    ),
    (
        "Can you help me explain something complicated in simple terms?",
        "Absolutely — that's one of my favourite things to do. "
        "What topic would you like me to break down?",
    ),
    (
        "Thanks for your help!",
        "You're very welcome! Feel free to come back any time. "
        "Is there anything else on your mind?",
    ),
]


# ---------------------------------------------------------------------------
# BatchGenerator
# ---------------------------------------------------------------------------


class BatchGenerator:
    """
    Generates a training batch for one sleep cycle.

    Usage:
        gen = BatchGenerator(config)
        examples, meta = gen.build_cycle_batch(
            new_memories, consolidated, dialogue_by_day, seed=42
        )
    """

    def __init__(self, config: dict) -> None:
        m = config["batch_mixture"]
        self.decl_ratio  = float(m["declarative_ratio"])
        self.qa_ratio    = float(m["qa_ratio"])
        self.dial_ratio  = float(m["dialogue_ratio"])
        self.qa_per_fact = int(m.get("qa_phrasings_per_fact", 3))

        self.qa_templates: list[str] = config["qa_train_templates"]

        r = config["replay_buffer"]
        self.replay_enabled = bool(r["enabled"])
        self.replay_ratio   = float(r["historical_sample_ratio"])

        reg = config.get("regularizer", {})
        self.reg_enabled = bool(reg.get("enabled", True))
        self.reg_n       = int(reg.get("generic_dialogue_samples", 10))

        am = config.get("anti_memory", {})
        self.anti_memory_cfg_enabled = bool(am.get("enabled", False))
        self.anti_pairs_per_update   = int(am.get("pairs_per_update", 2))

        self._rng = random.Random()

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def build_cycle_batch(
        self,
        new_memories: list[dict],
        consolidated_memories: list[dict],
        dialogue_by_day: dict[int, list[dict]],
        seed: int = 42,
        anti_memory_enabled: bool = False,
        all_memories: list[dict] | None = None,
    ) -> tuple[list[list[dict]], dict[str, Any]]:
        """
        Build one training batch for a sleep cycle.

        Args:
            new_memories:          Un-consolidated memories from the current window.
            consolidated_memories: All previously consolidated memories (replay pool).
            dialogue_by_day:       {day: [turn_dict]} for dialogue snippet extraction.
            seed:                  RNG seed for reproducibility.
            anti_memory_enabled:   If True (and config anti_memory.enabled is True),
                                   generate Anti-Memory QA pairs for update memories.
            all_memories:          Full memory pool needed to look up superseded facts
                                   when building Anti-Memory pairs. If None and
                                   anti_memory is enabled, builds a lookup from
                                   new + consolidated memories.

        Returns:
            examples:   List of message-lists in HF chat format.
            meta:       Dict with counts, memory_ids, and per-component sizes.
        """
        self._rng.seed(seed)

        # Build a fast id→memory lookup for Anti-Memory superseded-fact lookup
        _use_anti = anti_memory_enabled and self.anti_memory_cfg_enabled
        _mem_by_id: dict[str, dict] = {}
        if _use_anti:
            pool = (all_memories or []) + new_memories + consolidated_memories
            _mem_by_id = {m["memory_id"]: m for m in pool if m.get("memory_id")}

        examples: list[list[dict]] = []
        memory_ids: list[str] = []
        n_decl = n_qa = n_dial = n_replay = n_anti = 0

        # --- New memories: expand via batch mixture ---
        for mem in new_memories:
            new_ex, d, q, dl = self._expand_memory(mem, dialogue_by_day)
            examples.extend(new_ex)
            memory_ids.append(mem["memory_id"])
            n_decl += d; n_qa += q; n_dial += dl

            # Anti-Memory pairs for update memories
            if _use_anti and mem.get("is_update") and mem.get("supersedes_memory_id"):
                old_mem = _mem_by_id.get(mem["supersedes_memory_id"])
                if old_mem:
                    anti_ex = self._anti_memory_examples(old_mem, mem)
                    examples.extend(anti_ex)
                    n_anti += len(anti_ex)

        # --- Replay buffer ---
        if self.replay_enabled and consolidated_memories:
            n_sample = max(1, round(len(new_memories) * self.replay_ratio))
            replay_mems = self._sample_replay(consolidated_memories, n_sample)
            for mem in replay_mems:
                rep_ex, _, _, _ = self._expand_memory(mem, dialogue_by_day)
                examples.extend(rep_ex)
                memory_ids.append(mem["memory_id"])
                n_replay += len(rep_ex)

        # --- Regularizer ---
        n_reg = 0
        if self.reg_enabled:
            reg_pairs = self._rng.sample(
                _REGULARIZER_EXCHANGES,
                min(self.reg_n, len(_REGULARIZER_EXCHANGES)),
            )
            for user_msg, asst_msg in reg_pairs:
                examples.append([
                    {"role": "user",      "content": user_msg},
                    {"role": "assistant", "content": asst_msg},
                ])
                n_reg += 1

        self._rng.shuffle(examples)

        meta = {
            "memory_ids":     memory_ids,
            "n_total":        len(examples),
            "n_declarative":  n_decl,
            "n_qa":           n_qa,
            "n_dialogue":     n_dial,
            "n_replay":       n_replay,
            "n_regularizer":  n_reg,
            "n_anti_memory":  n_anti,
        }
        return examples, meta

    # ------------------------------------------------------------------
    # Memory expansion
    # ------------------------------------------------------------------

    def _expand_memory(
        self,
        mem: dict,
        dialogue_by_day: dict[int, list[dict]],
    ) -> tuple[list[list[dict]], int, int, int]:
        """
        Expand one memory item into declarative + QA + dialogue examples.
        Returns (examples, n_decl, n_qa, n_dial).
        """
        examples: list[list[dict]] = []
        n_decl = n_qa = n_dial = 0

        # Declarative
        examples.append(self._declarative(mem))
        n_decl += 1

        # QA probes — strictly from config templates only
        qa_pairs = self._qa_pairs(mem)
        selected = self._rng.sample(
            qa_pairs, min(self.qa_per_fact, len(qa_pairs))
        ) if qa_pairs else []
        for q, a in selected:
            examples.append([
                {"role": "system",    "content": _SYS_RECALL},
                {"role": "user",      "content": q},
                {"role": "assistant", "content": a},
            ])
            n_qa += 1

        # Dialogue snippet
        snippet = self._dialogue_snippet(mem, dialogue_by_day)
        if snippet:
            examples.append(snippet)
            n_dial += 1

        return examples, n_decl, n_qa, n_dial

    def _declarative(self, mem: dict) -> list[dict]:
        subj = mem["subject"]
        pred = mem["predicate"]
        val  = mem["value"] if isinstance(mem["value"], str) else json.dumps(mem["value"])
        fact = f"{subj} {pred} {val}."
        return [
            {"role": "system",    "content": _SYS_REMEMBER},
            {"role": "user",      "content": f"Remember this: {fact}"},
            {"role": "assistant", "content": f"Noted. {fact}"},
        ]

    def _qa_pairs(self, mem: dict) -> list[tuple[str, str]]:
        """
        Fill each config QA template with subject / predicate / category / value.
        Derives {category} via the same mapper used in Phase 3/4.
        Falls back to {predicate} if no category is found.
        """
        subj = mem["subject"]
        pred = mem["predicate"]
        val  = mem["value"] if isinstance(mem["value"], str) else json.dumps(mem["value"])
        cat  = _map_category((pred + " " + val).lower()) or pred

        answer = f"{subj} {pred} {val}."
        pairs: list[tuple[str, str]] = []
        for tmpl in self.qa_templates:
            try:
                question = tmpl.format(
                    subject=subj,
                    predicate=pred,
                    category=cat,
                )
                pairs.append((question, answer))
            except KeyError:
                # Template uses a placeholder not available — skip silently
                continue
        return pairs

    def _dialogue_snippet(
        self,
        mem: dict,
        dialogue_by_day: dict[int, list[dict]],
    ) -> list[dict] | None:
        """
        Find a 2–3 turn window from mem['day'] that best proves the fact.

        Strategy:
          1. Find the user turn on that day with highest token overlap
             with the memory's predicate + value.
          2. Expand to a window: [turn_before, matched_turn, turn_after]
             (capped at available turns).
          3. Format as HF chat messages (user/assistant roles).

        Returns None if no matching turn is found or the window is < 2 turns.
        """
        day_turns: list[dict] = dialogue_by_day.get(mem["day"], [])
        if len(day_turns) < 2:
            return None

        val_str = mem["value"] if isinstance(mem["value"], str) else json.dumps(mem["value"])
        key_toks = _primary_tokens((mem["predicate"] + " " + val_str).lower())
        if not key_toks:
            return None

        # Find best-matching USER turn
        best_idx, best_score = -1, 0
        for i, turn in enumerate(day_turns):
            if turn["speaker"] != "user":
                continue
            overlap = len(key_toks & _primary_tokens(turn["utterance"].lower()))
            if overlap > best_score:
                best_score, best_idx = overlap, i

        if best_idx == -1 or best_score == 0:
            return None

        # Expand to a 2–3 turn window (keep one turn before and one after)
        start = max(0, best_idx - 1)
        end   = min(len(day_turns), best_idx + 2)
        window = day_turns[start:end]

        messages = [
            {
                "role": "user" if t["speaker"] == "user" else "assistant",
                "content": t["utterance"],
            }
            for t in window
        ]
        # Need at least user + assistant for a meaningful exchange
        return messages if len(messages) >= 2 else None

    # ------------------------------------------------------------------
    # Anti-Memory: negative training for superseded facts
    # ------------------------------------------------------------------

    # Probe templates that challenge the OLD (stale) state.
    # The model must actively reject the premise and supply the new state.
    _ANTI_PROBE_TEMPLATES: list[str] = [
        "Is {subject} still {old_pred} {old_val}?",
        "{subject} {old_pred} {old_val}, right?",
        "I heard {subject} {old_pred} {old_val} — is that still true?",
        "Does {subject} still {old_pred} {old_val}?",
    ]

    def _anti_memory_examples(
        self,
        old_mem: dict,
        new_mem: dict,
    ) -> list[list[dict]]:
        """
        Generate Anti-Memory QA pairs that force the model to reject the stale
        state and supply the updated state.

        Example:
          old_mem: "Alice lives in Seattle, WA"
          new_mem: "Alice lives in Austin, TX"
          → Probe:  "Is Alice still lives in Seattle, WA?"
          → Target: "No — Alice lives in Austin, TX now."
        """
        subj     = new_mem.get("subject", "")
        old_pred = old_mem.get("predicate", "")
        old_val  = old_mem.get("value",     "")
        new_pred = new_mem.get("predicate", "")
        new_val  = new_mem.get("value",     "")

        if not (subj and old_val and new_val):
            return []

        answer = f"No — {subj} {new_pred} {new_val} now."

        templates = self._rng.sample(
            self._ANTI_PROBE_TEMPLATES,
            min(self.anti_pairs_per_update, len(self._ANTI_PROBE_TEMPLATES)),
        )

        examples: list[list[dict]] = []
        for tmpl in templates:
            try:
                question = tmpl.format(
                    subject=subj,
                    old_pred=old_pred,
                    old_val=old_val,
                )
                examples.append([
                    {"role": "system",    "content": _SYS_RECALL},
                    {"role": "user",      "content": question},
                    {"role": "assistant", "content": answer},
                ])
            except KeyError:
                continue
        return examples

    # ------------------------------------------------------------------
    # Replay buffer sampling
    # ------------------------------------------------------------------

    def _sample_replay(
        self,
        consolidated: list[dict],
        n: int,
    ) -> list[dict]:
        """
        Weighted random sample from consolidated memories.
        Weight = salience_score × temporal_decay (Phase 4 fields).
        Falls back to uniform sampling if weights are unavailable.
        """
        n = min(n, len(consolidated))
        weights = [
            max(1e-6,
                float(m.get("salience_score") or 0.5) *
                float(m.get("temporal_decay") or 1.0))
            for m in consolidated
        ]
        return self._rng.choices(consolidated, weights=weights, k=n)
