"""
analysis/rescore_deterministic.py
Re-score existing eval JSONs using the deterministic judge.

Rewrites score_label / score_numeric / judge_reason / judge_method fields
for stable, updated, and superseded buckets.  Relational scores are kept as-is
(LLM-judged).

Usage:
    python3 analysis/rescore_deterministic.py [--results-dir results/paper]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _add_src_to_path() -> None:
    """Allow importing from src/ without installing the package."""
    repo_root = Path(__file__).resolve().parent.parent
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))


_add_src_to_path()

from src.eval.judge import _det_score_stable_updated, _det_score_superseded  # noqa: E402


def rescore_file(eval_path: Path, probes_by_id: dict) -> tuple[int, int]:
    """
    Re-score one *_eval.json file in-place.
    Returns (n_rescored, n_kept_llm).
    """
    items: list[dict] = json.loads(eval_path.read_text())
    if not isinstance(items, list):
        return 0, 0

    n_rescored = n_llm = 0
    for item in items:
        bucket = item.get("bucket", "")
        if bucket not in ("stable", "updated", "superseded"):
            n_llm += 1
            continue

        probe = probes_by_id.get(item.get("probe_id", ""), {})
        # Merge probe data into item for the scorer helpers that read
        # probe["expected"] and probe["assertion_claim"].
        merged_probe = {
            "expected":        item.get("expected", probe.get("expected", "")),
            "assertion_claim": item.get("assertion_claim", probe.get("assertion_claim")),
            "persona_name":    item.get("persona_name", probe.get("persona_name", "")),
        }

        if bucket == "superseded":
            result = _det_score_superseded(merged_probe, item["response"])
        else:
            result = _det_score_stable_updated(merged_probe, item["response"])

        item["score_label"]   = result["score_label"]
        item["score_numeric"] = {"correct": 1.0, "partial": 0.5}.get(result["score_label"], 0.0)
        item["judge_reason"]  = result["judge_reason"]
        item["judge_method"]  = "deterministic"
        n_rescored += 1

    eval_path.write_text(json.dumps(items, indent=2))
    return n_rescored, n_llm


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir",  default="results/paper")
    parser.add_argument("--probes-file",  default="data/eval_probes/probes.json")
    parser.add_argument("--dry-run",      action="store_true",
                        help="Print what would be changed without writing")
    args = parser.parse_args()

    results_dir = Path(args.results_dir)
    probes_file = Path(args.probes_file)

    # Load probe index for assertion_claim look-up.
    probes_by_id: dict[str, dict] = {}
    if probes_file.exists():
        for p in json.loads(probes_file.read_text()):
            probes_by_id[p["probe_id"]] = p
        print(f"Loaded {len(probes_by_id)} probes from {probes_file}")

    eval_files = sorted(results_dir.rglob("*_eval.json"))
    # Skip RAG eval files — those will be regenerated by Objective 3.
    eval_files = [f for f in eval_files if not f.name.startswith("rag_")]

    print(f"Found {len(eval_files)} eval files to re-score (RAG excluded).")

    total_rescored = total_llm = total_files = 0
    for ef in eval_files:
        if args.dry_run:
            print(f"  [dry-run] would rescore {ef}")
            continue
        n_r, n_l = rescore_file(ef, probes_by_id)
        total_rescored += n_r
        total_llm      += n_l
        total_files    += 1

    if not args.dry_run:
        print(f"\nDone. Re-scored {total_rescored} items (deterministic) across {total_files} files.")
        print(f"Kept {total_llm} relational items as LLM-scored.")


if __name__ == "__main__":
    main()
